---
- name: Configuration Backups
  hosts: all
  connection: network_cli
  gather_facts: no
  ansible_network_os: ios
  
  tasks:
    - name: gather ios_facts
      ios_facts:
      register: version

    - debug:
        msg: "{{version}}"

    - name: Backup configuration
      ios_config:
        backup: yes
