---
- name: Configuration Backups
  hosts: all
  ansible_user: {{ ANSIBLE_NET_USER }}
  ansible_ssh_pass: {{ ANSIBLE_NET_PASSWORD }}
  gather_facts: no
  tasks:
    - name: gather ios_facts
      ios_facts:
      register: version

    - debug:
        msg: "{{version}}"

    - name: Backup configuration
      ios_config:
        backup: yes
