- name: configure the login banner
  hosts: all
  connection: network_cli
  ios_banner:
    banner: login
    text: |
      this is my login banner
      that contains a multiline
      string
    state: present
