- name: configure the login banner
  hosts: all
  connection: network_cli
  become: yes
  become_method: enable
  
  tasks:
    - name: Update Login banner
      ios_banner:
        banner: login
        text: |
          this is my login banner
          that contains a multiline
          string
        state: present
