---
- hosts: all
  gather_facts: no
  connection: local
  
  tasks:
  - name: show configuration
    ios_command:
      commands: show running-config
    register: new_host
    
  - debug: msg="{{ new_host.stdout }}"
